version: '3.8'

services:
  fyle-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fyle-backend
    image: fyle-backend-intern
    ports:
      - "7755:7755"
    command: ["bash","run.sh"]
